### ISSUE TITLE
Broken controls leading to bad UX

### ISSUE THREAD

**Issue by KyleSanderson** [agateau/pixelwheels#204]
## Describe the bug

Android phones since the beginning of time have had an accelerometer. Mario Kart seems to have gotten this right by having tilt controls as opposed to buttons.

## Explain what went wrong

Ergonomics.

### How to reproduce

1.  Run the game
2. 
3. 

### Expected behavior

Tilting the handset when it's in forced landscape mode drives the vehicle.

## What should have happened instead?

A prompt asking if I would prefer buttons, defaulting to decline.

## Information about your build

F-droid

Pixel Wheels version:

Binary origin:
- [ ] itch.io
- [ ] Google Play
- [x] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version: 11

## Optional information

If relevant, add screenshots to help explain the bug.

## Additional context

If you generated a log archive from the game, you can attach it to this report.

**Comment by agateau** [comment]
Hi Kyle,

I too thought it would be a good idea to have accelerometer-based control, so I experimented with it, but I found out it does not work. It makes sense in a 3D game, because the camera is behind the player, but it is unusable in a top-down game, especially when the vehicle is pointing down.
