### ISSUE TITLE
Dev. Options are available only in English (translations not possible)

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#342]
Dev. Options sentences are not present in translation files but only in [core/src/com/agateau/pixelwheels/screens/DebugScreen.java](https://github.com/agateau/pixelwheels/blob/master/core/src/com/agateau/pixelwheels/screens/DebugScreen.java).

It would be nice if all menu/settings screens could be translated into the chosen language.

**Comment by agateau** [comment]
when I started making the game translatable I wondered if I should make this screen translatable too but decided not to because:
- it creates more work for translators, for a part which is not needed by players and  may go away or become less accessible at some point
- some of the content barely fits the screen, and I don't want to deal with the sizing issues caused by translations
