### ISSUE TITLE
Do not register high score when debug options are active (was: Does changing debug settings affects the original highscores?)

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#35]
hi :3

i don't think that it the answer is clear in the settings: if i were to get a better highscore with the debug settings changed, would that score still register the ones i've got without 'cheating'?

an info at the debug settings screen would be nice to inform that :3

thank you \^w\^

**Comment by agateau** [comment]
Yes, debug settings affects the highscores, so you can easily cheat for now. Those settings will be disabled in the final version.

**Comment by Wilker-a** [comment]
i think it would be better if the debug mode simply disabled score registering or something. i like the customization

**Comment by agateau** [comment]
Sounds like a good idea :+1:. Rephrasing and reopening.

**Comment by Eiim** [comment]
Although this was supposedly fixed in 298f73c, the issue still seems to persist in 0.20.0 on Android. In this screenshot, I did a run with Red with one lap mode on and naturally easily beat all my previous legitimately-obtained records, and it counted in the scoreboard.
![image](https://user-images.githubusercontent.com/24627058/128440995-77394b49-b01c-4014-a0b3-989b218380b6.png)

**Comment by agateau** [comment]
It counted, but did the score survive a restart?

**Comment by Eiim** [comment]
Yep, it (plus one other such test run) is still there, and I've restarted both the game and my phone since.
![image](https://user-images.githubusercontent.com/24627058/129820463-480b7886-e3f3-4eb8-b936-b735689ac37b.png)

**Comment by agateau** [comment]
OK, going to reopen this then.
