### ISSUE TITLE
Stuck in a tree

### ISSUE THREAD

**Issue by Kharaje** [agateau/pixelwheels#418]
![Screenshot_2023-10-10-21-52-40-689_com agateau tinywheels android](https://github.com/agateau/pixelwheels/assets/147530570/2785111a-4563-49ce-8991-96b09be4beb2)
## Describe the bug

Explain what went wrong

### How to reproduce

1. Map: up, up and down
2. in the north of the highway, when turning left, I was shot from a machine gun by a rival coming from behind
3. I am in the forest. Thats all.

### Expected behavior

What should have happened instead?
- helicopter?:)

## Information about your build

Pixel Wheels version: 0.25.1

Binary origin:

- [ ] itch.io
- [ ] Google Play
- [x] F-Droid
- [ ] <https://builds.agateau.com/pixelwheels/>
- [ ] Self-built
- [ ] Other:

OS:

- [x] Android 

OS version: Miui 14.0.8

## Optional information

If relevant, add screenshots to help explain the bug.

## Additional context

**Comment by agateau** [comment]
Hi, sorry for the late reply. That is annoying indeed. I am considering changing the effects of getting hit by the gun. Instead of sending the vehicle spinning around, possibly ending stuck in trees, it would temporarily disable the engine, causing the vehicle to slow to a halt but staying in the same direction.
