### ISSUE TITLE
Open races

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#70]
perhaps this requires some more thinking:

what if the game had open races, like in the Midnight Club franchise, for example? a kind of city being made with various roads, and therefore routes for tracks, where these tracks have points to reach instead of a fixed route unless stated otherwise. with ordered and unordered races making the player memorize different routes of it to take advantage of...

what do you think?

**Comment by Obsidien** [comment]
Open races have the same problem, in my opinion, as larger maps (#37): you finish playing alone, instead of having fun with opponents; and in a phone game, it looks hard to have also a bunch of non-playing-cars (as can be done on computer games), so you’re really alone. Also, the AIs would probably always use the same paths, making the thing not specially interesting.

**Comment by Wilker-a** [comment]
for that problem, i mentioned at #55 a couple of possible solutions, including secondary waypoints for the AIs to follow and changing how the pathfinding works for adding more diversity to driving styles and whatnot.

also, maybe a catch-up mechanic for bots could also be considered, as that could mitigate the need for just adding more cars — 4~16 drivers are generally enough, depending just on the 'importance' of a race and the total playable area of a track (e.g how large (as in width) are the roads)

**Comment by agateau** [comment]
Sorry but this strays too much away from the original idea of the game. I want to be able to consider it "finished" at some point :)
