### ISSUE TITLE
Rocket is slow but perfectly regular

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#76]
Not sure how to present this bug, but the Rocket car just did on my pocket computer:
* best lap: 2:11.55;
* total: 6:34.65;

and that looks quite suspicious.

**Comment by agateau** [comment]
This is because it often gets stuck in the first lap, so the lap duration is extrapolated (if it got stuck at 80% of the track, Pixel Wheels defines its lap duration as time * 100 / 80) and the other laps uses the same duration.

This will go away when AI becomes less dumb, which is on my TODO list.

**Comment by Obsidien** [comment]
Even if this will less often be seen (normally) when AI becomes less dumb (and when cars stop being stuck, as it can happen, notably for Rocket), it might not be so difficult to close the bug “for real”, by just adding some random somewhere when doing that… Is that a bad idea?

Other bug or not? In the same vain, I have seen Pickup do:
* best lap: 0:17.72;
* total: 0:49.34;
and this is probably even worse, if you think about it.

**Comment by agateau** [comment]
I don't think it's worth spending time on this for now. I expect bots won't be stuck for the whole race when they become smarter.
